name: Flask Hello World

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/docker-login@v1
      with:
        login-server: checkcontainertest.azurecr.io
        username: ${{ secrets.AZURE_CR_USERNAME }}
        password: ${{ secrets.AZURE_CR_PASSWORD }}
    - run: |
        docker build . -t checkcontainertest.azurecr.io/myapp:${{ github.sha }}
        docker push checkcontainertest.azurecr.io/myapp:${{ github.sha }}


  deploy:
        runs-on: ubuntu-latest
        needs: build
        
        environment:
          name: 'production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
        steps:
          - uses: azure/docker-login@v1
            with:
              login-server: checkcontainertest.azurecr.io
              username: ${{ secrets.AZURE_CR_USERNAME }}
              password: ${{ secrets.AZURE_CR_PASSWORD }}
        
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'dockercontainertestchethan'
              slot-name: 'production'
              publish-profile: ${{ secrets.AzureAppService_PublishProfile_02 }}
              images: 'checkcontainertest.azurecr.io/myapp:${{ github.sha }}'
