name: Flask Hello World

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: rockingkiran2000/flask-helloworld::${{ github.sha }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
        runs-on: ubuntu-latest
        needs: build
        
        environment:
          name: 'production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
        steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'dockercontainertestchethan'
              slot-name: 'production'
              publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
              images: 'index.docker.io/rockingkiran2000/flask-helloworld:${{ github.sha }}'
